# coding: utf-8

"""
    Investoreight Core API

    Investoreight API Documentation:  https://api.investoreight.com/api-docs/index.html  # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: info@investoreight.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import investor8_sdk
from investor8_sdk.models.create_screen_dto import CreateScreenDto  # noqa: E501
from investor8_sdk.rest import ApiException


class TestCreateScreenDto(unittest.TestCase):
    """CreateScreenDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateScreenDto(self):
        """Test CreateScreenDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = investor8_sdk.models.create_screen_dto.CreateScreenDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
