# coding: utf-8

"""
    Investor8.Core

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import investor8_sdk
from investor8_sdk.models.authentication_source import AuthenticationSource  # noqa: E501
from investor8_sdk.rest import ApiException


class TestAuthenticationSource(unittest.TestCase):
    """AuthenticationSource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuthenticationSource(self):
        """Test AuthenticationSource"""
        # FIXME: construct object with mandatory attributes with example values
        # model = investor8_sdk.models.authentication_source.AuthenticationSource()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
