# coding: utf-8

"""
    Investor8.Core

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import investor8_sdk
from investor8_sdk.models.financial_tag import FinancialTag  # noqa: E501
from investor8_sdk.rest import ApiException


class TestFinancialTag(unittest.TestCase):
    """FinancialTag unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFinancialTag(self):
        """Test FinancialTag"""
        # FIXME: construct object with mandatory attributes with example values
        # model = investor8_sdk.models.financial_tag.FinancialTag()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
