# coding: utf-8

"""
    Investor8.Core

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import investor8_sdk
from investor8_sdk.api.earnings_api import EarningsApi  # noqa: E501
from investor8_sdk.rest import ApiException


class TestEarningsApi(unittest.TestCase):
    """EarningsApi unit test stubs"""

    def setUp(self):
        self.api = EarningsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_earnings_by_date(self):
        """Test case for get_earnings_by_date

        """
        pass

    def test_get_historical_earnings(self):
        """Test case for get_historical_earnings

        """
        pass

    def test_get_recent_earnings(self):
        """Test case for get_recent_earnings

        """
        pass

    def test_get_today_earnings(self):
        """Test case for get_today_earnings

        """
        pass

    def test_get_upcoming_earning(self):
        """Test case for get_upcoming_earning

        """
        pass

    def test_get_upcoming_earnings(self):
        """Test case for get_upcoming_earnings

        """
        pass


if __name__ == '__main__':
    unittest.main()
