# coding: utf-8

"""
    Investor8.Core

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import investor8_sdk
from investor8_sdk.api.price_api import PriceApi  # noqa: E501
from investor8_sdk.rest import ApiException


class TestPriceApi(unittest.TestCase):
    """PriceApi unit test stubs"""

    def setUp(self):
        self.api = PriceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_all_latest_prices(self):
        """Test case for get_all_latest_prices

        """
        pass

    def test_get_all_previous_closes(self):
        """Test case for get_all_previous_closes

        """
        pass

    def test_get_historical_prices(self):
        """Test case for get_historical_prices

        """
        pass

    def test_get_latest_market_indices(self):
        """Test case for get_latest_market_indices

        """
        pass

    def test_get_latest_price(self):
        """Test case for get_latest_price

        """
        pass


if __name__ == '__main__':
    unittest.main()
