# coding: utf-8

"""
    Investor8.Core

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import investor8_sdk
from investor8_sdk.models.previous_close_dto import PreviousCloseDto  # noqa: E501
from investor8_sdk.rest import ApiException


class TestPreviousCloseDto(unittest.TestCase):
    """PreviousCloseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPreviousCloseDto(self):
        """Test PreviousCloseDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = investor8_sdk.models.previous_close_dto.PreviousCloseDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
