# coding: utf-8

"""
    Investor8.Core

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import investor8_sdk
from investor8_sdk.models.metadata_properties_dto import MetadataPropertiesDto  # noqa: E501
from investor8_sdk.rest import ApiException


class TestMetadataPropertiesDto(unittest.TestCase):
    """MetadataPropertiesDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMetadataPropertiesDto(self):
        """Test MetadataPropertiesDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = investor8_sdk.models.metadata_properties_dto.MetadataPropertiesDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
