# coding: utf-8

"""
    Investor8.Core

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import investor8_sdk
from investor8_sdk.models.history_length import HistoryLength  # noqa: E501
from investor8_sdk.rest import ApiException


class TestHistoryLength(unittest.TestCase):
    """HistoryLength unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHistoryLength(self):
        """Test HistoryLength"""
        # FIXME: construct object with mandatory attributes with example values
        # model = investor8_sdk.models.history_length.HistoryLength()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
