# coding: utf-8

"""
    Investor8.Core

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import investor8_sdk
from investor8_sdk.api.news_api import NewsApi  # noqa: E501
from investor8_sdk.rest import ApiException


class TestNewsApi(unittest.TestCase):
    """NewsApi unit test stubs"""

    def setUp(self):
        self.api = NewsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_market_highlight(self):
        """Test case for add_market_highlight

        """
        pass

    def test_add_news(self):
        """Test case for add_news

        """
        pass

    def test_delete_market_highlight(self):
        """Test case for delete_market_highlight

        """
        pass

    def test_get(self):
        """Test case for get

        """
        pass

    def test_get_aggregated_ticker_news(self):
        """Test case for get_aggregated_ticker_news

        """
        pass

    def test_get_all_sectors_news(self):
        """Test case for get_all_sectors_news

        """
        pass

    def test_get_latest_highlight_news(self):
        """Test case for get_latest_highlight_news

        """
        pass

    def test_get_latest_news(self):
        """Test case for get_latest_news

        """
        pass

    def test_get_latest_news_ext(self):
        """Test case for get_latest_news_ext

        """
        pass

    def test_get_list_highlights_by_id(self):
        """Test case for get_list_highlights_by_id

        """
        pass

    def test_get_market_highlight(self):
        """Test case for get_market_highlight

        """
        pass

    def test_get_market_highlights(self):
        """Test case for get_market_highlights

        """
        pass

    def test_get_news_by_category(self):
        """Test case for get_news_by_category

        """
        pass

    def test_get_news_by_sector(self):
        """Test case for get_news_by_sector

        """
        pass

    def test_get_news_categories(self):
        """Test case for get_news_categories

        """
        pass

    def test_get_news_list(self):
        """Test case for get_news_list

        """
        pass

    def test_get_ticker_news(self):
        """Test case for get_ticker_news

        """
        pass

    def test_get_tickers_with_news(self):
        """Test case for get_tickers_with_news

        """
        pass

    def test_get_top_news(self):
        """Test case for get_top_news

        """
        pass

    def test_update_market_highlight(self):
        """Test case for update_market_highlight

        """
        pass

    def test_update_news(self):
        """Test case for update_news

        """
        pass


if __name__ == '__main__':
    unittest.main()
