# coding: utf-8

"""
    Investor8.Core

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import investor8_sdk
from investor8_sdk.api.email_api import EmailApi  # noqa: E501
from investor8_sdk.rest import ApiException


class TestEmailApi(unittest.TestCase):
    """EmailApi unit test stubs"""

    def setUp(self):
        self.api = EmailApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_schedule_email(self):
        """Test case for schedule_email

        """
        pass

    def test_send_email(self):
        """Test case for send_email

        """
        pass


if __name__ == '__main__':
    unittest.main()
