# coding: utf-8

"""
    Investor8.Core

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UpdatePlotDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'is_public': 'bool',
        'title': 'str',
        'user_notes': 'str',
        'tags': 'list[str]'
    }

    attribute_map = {
        'id': 'Id',
        'is_public': 'IsPublic',
        'title': 'Title',
        'user_notes': 'UserNotes',
        'tags': 'Tags'
    }

    def __init__(self, id=None, is_public=None, title=None, user_notes=None, tags=None):  # noqa: E501
        """UpdatePlotDto - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._is_public = None
        self._title = None
        self._user_notes = None
        self._tags = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if is_public is not None:
            self.is_public = is_public
        if title is not None:
            self.title = title
        if user_notes is not None:
            self.user_notes = user_notes
        if tags is not None:
            self.tags = tags

    @property
    def id(self):
        """Gets the id of this UpdatePlotDto.  # noqa: E501


        :return: The id of this UpdatePlotDto.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this UpdatePlotDto.


        :param id: The id of this UpdatePlotDto.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def is_public(self):
        """Gets the is_public of this UpdatePlotDto.  # noqa: E501


        :return: The is_public of this UpdatePlotDto.  # noqa: E501
        :rtype: bool
        """
        return self._is_public

    @is_public.setter
    def is_public(self, is_public):
        """Sets the is_public of this UpdatePlotDto.


        :param is_public: The is_public of this UpdatePlotDto.  # noqa: E501
        :type: bool
        """

        self._is_public = is_public

    @property
    def title(self):
        """Gets the title of this UpdatePlotDto.  # noqa: E501


        :return: The title of this UpdatePlotDto.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this UpdatePlotDto.


        :param title: The title of this UpdatePlotDto.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def user_notes(self):
        """Gets the user_notes of this UpdatePlotDto.  # noqa: E501


        :return: The user_notes of this UpdatePlotDto.  # noqa: E501
        :rtype: str
        """
        return self._user_notes

    @user_notes.setter
    def user_notes(self, user_notes):
        """Sets the user_notes of this UpdatePlotDto.


        :param user_notes: The user_notes of this UpdatePlotDto.  # noqa: E501
        :type: str
        """

        self._user_notes = user_notes

    @property
    def tags(self):
        """Gets the tags of this UpdatePlotDto.  # noqa: E501


        :return: The tags of this UpdatePlotDto.  # noqa: E501
        :rtype: list[str]
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this UpdatePlotDto.


        :param tags: The tags of this UpdatePlotDto.  # noqa: E501
        :type: list[str]
        """

        self._tags = tags

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UpdatePlotDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UpdatePlotDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
