# coding: utf-8

"""
    Investoreight Core API

    Investoreight API Documentation:  https://api.investoreight.com/api-docs/index.html  # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: info@investoreight.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GetListMetricsDescriptionDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'metric_name': 'str',
        'display_name': 'str',
        'description': 'str'
    }

    attribute_map = {
        'id': 'Id',
        'metric_name': 'MetricName',
        'display_name': 'DisplayName',
        'description': 'Description'
    }

    def __init__(self, id=None, metric_name=None, display_name=None, description=None):  # noqa: E501
        """GetListMetricsDescriptionDto - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._metric_name = None
        self._display_name = None
        self._description = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if metric_name is not None:
            self.metric_name = metric_name
        if display_name is not None:
            self.display_name = display_name
        if description is not None:
            self.description = description

    @property
    def id(self):
        """Gets the id of this GetListMetricsDescriptionDto.  # noqa: E501


        :return: The id of this GetListMetricsDescriptionDto.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this GetListMetricsDescriptionDto.


        :param id: The id of this GetListMetricsDescriptionDto.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def metric_name(self):
        """Gets the metric_name of this GetListMetricsDescriptionDto.  # noqa: E501


        :return: The metric_name of this GetListMetricsDescriptionDto.  # noqa: E501
        :rtype: str
        """
        return self._metric_name

    @metric_name.setter
    def metric_name(self, metric_name):
        """Sets the metric_name of this GetListMetricsDescriptionDto.


        :param metric_name: The metric_name of this GetListMetricsDescriptionDto.  # noqa: E501
        :type: str
        """

        self._metric_name = metric_name

    @property
    def display_name(self):
        """Gets the display_name of this GetListMetricsDescriptionDto.  # noqa: E501


        :return: The display_name of this GetListMetricsDescriptionDto.  # noqa: E501
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name):
        """Sets the display_name of this GetListMetricsDescriptionDto.


        :param display_name: The display_name of this GetListMetricsDescriptionDto.  # noqa: E501
        :type: str
        """

        self._display_name = display_name

    @property
    def description(self):
        """Gets the description of this GetListMetricsDescriptionDto.  # noqa: E501


        :return: The description of this GetListMetricsDescriptionDto.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this GetListMetricsDescriptionDto.


        :param description: The description of this GetListMetricsDescriptionDto.  # noqa: E501
        :type: str
        """

        self._description = description

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetListMetricsDescriptionDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetListMetricsDescriptionDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
