# coding: utf-8

"""
    Investor8.Core

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ListExchangeSectorDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'exchange': 'list[str]',
        'sector': 'list[str]'
    }

    attribute_map = {
        'exchange': 'Exchange',
        'sector': 'Sector'
    }

    def __init__(self, exchange=None, sector=None):  # noqa: E501
        """ListExchangeSectorDto - a model defined in Swagger"""  # noqa: E501
        self._exchange = None
        self._sector = None
        self.discriminator = None
        if exchange is not None:
            self.exchange = exchange
        if sector is not None:
            self.sector = sector

    @property
    def exchange(self):
        """Gets the exchange of this ListExchangeSectorDto.  # noqa: E501


        :return: The exchange of this ListExchangeSectorDto.  # noqa: E501
        :rtype: list[str]
        """
        return self._exchange

    @exchange.setter
    def exchange(self, exchange):
        """Sets the exchange of this ListExchangeSectorDto.


        :param exchange: The exchange of this ListExchangeSectorDto.  # noqa: E501
        :type: list[str]
        """

        self._exchange = exchange

    @property
    def sector(self):
        """Gets the sector of this ListExchangeSectorDto.  # noqa: E501


        :return: The sector of this ListExchangeSectorDto.  # noqa: E501
        :rtype: list[str]
        """
        return self._sector

    @sector.setter
    def sector(self, sector):
        """Sets the sector of this ListExchangeSectorDto.


        :param sector: The sector of this ListExchangeSectorDto.  # noqa: E501
        :type: list[str]
        """

        self._sector = sector

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ListExchangeSectorDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ListExchangeSectorDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
