# coding: utf-8

"""
    Investoreight Core API

    Investoreight API Documentation:  https://api.investoreight.com/api-docs/index.html  # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: info@investoreight.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MetricsByPeriodDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'symbol': 'str',
        'metric': 'str',
        'value': 'str',
        'value_numeric': 'float',
        'period': 'str',
        'period_type': 'str',
        'period_date_time': 'datetime'
    }

    attribute_map = {
        'id': 'Id',
        'symbol': 'Symbol',
        'metric': 'Metric',
        'value': 'Value',
        'value_numeric': 'ValueNumeric',
        'period': 'Period',
        'period_type': 'PeriodType',
        'period_date_time': 'PeriodDateTime'
    }

    def __init__(self, id=None, symbol=None, metric=None, value=None, value_numeric=None, period=None, period_type=None, period_date_time=None):  # noqa: E501
        """MetricsByPeriodDto - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._symbol = None
        self._metric = None
        self._value = None
        self._value_numeric = None
        self._period = None
        self._period_type = None
        self._period_date_time = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if symbol is not None:
            self.symbol = symbol
        if metric is not None:
            self.metric = metric
        if value is not None:
            self.value = value
        if value_numeric is not None:
            self.value_numeric = value_numeric
        if period is not None:
            self.period = period
        if period_type is not None:
            self.period_type = period_type
        if period_date_time is not None:
            self.period_date_time = period_date_time

    @property
    def id(self):
        """Gets the id of this MetricsByPeriodDto.  # noqa: E501


        :return: The id of this MetricsByPeriodDto.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this MetricsByPeriodDto.


        :param id: The id of this MetricsByPeriodDto.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def symbol(self):
        """Gets the symbol of this MetricsByPeriodDto.  # noqa: E501


        :return: The symbol of this MetricsByPeriodDto.  # noqa: E501
        :rtype: str
        """
        return self._symbol

    @symbol.setter
    def symbol(self, symbol):
        """Sets the symbol of this MetricsByPeriodDto.


        :param symbol: The symbol of this MetricsByPeriodDto.  # noqa: E501
        :type: str
        """

        self._symbol = symbol

    @property
    def metric(self):
        """Gets the metric of this MetricsByPeriodDto.  # noqa: E501


        :return: The metric of this MetricsByPeriodDto.  # noqa: E501
        :rtype: str
        """
        return self._metric

    @metric.setter
    def metric(self, metric):
        """Sets the metric of this MetricsByPeriodDto.


        :param metric: The metric of this MetricsByPeriodDto.  # noqa: E501
        :type: str
        """

        self._metric = metric

    @property
    def value(self):
        """Gets the value of this MetricsByPeriodDto.  # noqa: E501


        :return: The value of this MetricsByPeriodDto.  # noqa: E501
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this MetricsByPeriodDto.


        :param value: The value of this MetricsByPeriodDto.  # noqa: E501
        :type: str
        """

        self._value = value

    @property
    def value_numeric(self):
        """Gets the value_numeric of this MetricsByPeriodDto.  # noqa: E501


        :return: The value_numeric of this MetricsByPeriodDto.  # noqa: E501
        :rtype: float
        """
        return self._value_numeric

    @value_numeric.setter
    def value_numeric(self, value_numeric):
        """Sets the value_numeric of this MetricsByPeriodDto.


        :param value_numeric: The value_numeric of this MetricsByPeriodDto.  # noqa: E501
        :type: float
        """

        self._value_numeric = value_numeric

    @property
    def period(self):
        """Gets the period of this MetricsByPeriodDto.  # noqa: E501


        :return: The period of this MetricsByPeriodDto.  # noqa: E501
        :rtype: str
        """
        return self._period

    @period.setter
    def period(self, period):
        """Sets the period of this MetricsByPeriodDto.


        :param period: The period of this MetricsByPeriodDto.  # noqa: E501
        :type: str
        """

        self._period = period

    @property
    def period_type(self):
        """Gets the period_type of this MetricsByPeriodDto.  # noqa: E501


        :return: The period_type of this MetricsByPeriodDto.  # noqa: E501
        :rtype: str
        """
        return self._period_type

    @period_type.setter
    def period_type(self, period_type):
        """Sets the period_type of this MetricsByPeriodDto.


        :param period_type: The period_type of this MetricsByPeriodDto.  # noqa: E501
        :type: str
        """

        self._period_type = period_type

    @property
    def period_date_time(self):
        """Gets the period_date_time of this MetricsByPeriodDto.  # noqa: E501


        :return: The period_date_time of this MetricsByPeriodDto.  # noqa: E501
        :rtype: datetime
        """
        return self._period_date_time

    @period_date_time.setter
    def period_date_time(self, period_date_time):
        """Sets the period_date_time of this MetricsByPeriodDto.


        :param period_date_time: The period_date_time of this MetricsByPeriodDto.  # noqa: E501
        :type: datetime
        """

        self._period_date_time = period_date_time

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MetricsByPeriodDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MetricsByPeriodDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
