# coding: utf-8

"""
    Investor8.Core

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ViewPlotDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'plot_id': 'str'
    }

    attribute_map = {
        'plot_id': 'PlotId'
    }

    def __init__(self, plot_id=None):  # noqa: E501
        """ViewPlotDto - a model defined in Swagger"""  # noqa: E501
        self._plot_id = None
        self.discriminator = None
        self.plot_id = plot_id

    @property
    def plot_id(self):
        """Gets the plot_id of this ViewPlotDto.  # noqa: E501


        :return: The plot_id of this ViewPlotDto.  # noqa: E501
        :rtype: str
        """
        return self._plot_id

    @plot_id.setter
    def plot_id(self, plot_id):
        """Sets the plot_id of this ViewPlotDto.


        :param plot_id: The plot_id of this ViewPlotDto.  # noqa: E501
        :type: str
        """
        if plot_id is None:
            raise ValueError("Invalid value for `plot_id`, must not be `None`")  # noqa: E501

        self._plot_id = plot_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ViewPlotDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ViewPlotDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
