# coding: utf-8

# flake8: noqa
"""
    Investor8.Core

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from investor8-sdk.models.authentication_request import AuthenticationRequest
from investor8-sdk.models.change_password_dto import ChangePasswordDto
from investor8-sdk.models.company_info_dto import CompanyInfoDto
from investor8-sdk.models.create_plot_dto import CreatePlotDto
from investor8-sdk.models.create_update_news import CreateUpdateNews
from investor8-sdk.models.create_user_dto import CreateUserDto
from investor8-sdk.models.create_watchlist_dto import CreateWatchlistDto
from investor8-sdk.models.current_momentum_metrics_dto import CurrentMomentumMetricsDto
from investor8-sdk.models.daily_metrics_dto import DailyMetricsDto
from investor8-sdk.models.detailed_latest_price_dto import DetailedLatestPriceDto
from investor8-sdk.models.earning_metrics_dto import EarningMetricsDto
from investor8-sdk.models.email_type import EmailType
from investor8-sdk.models.financial_report_dto import FinancialReportDto
from investor8-sdk.models.financial_tag import FinancialTag
from investor8-sdk.models.financials_growth import FinancialsGrowth
from investor8-sdk.models.get_watchlists_by_user_dto import GetWatchlistsByUserDto
from investor8-sdk.models.historical_financial_metrics import HistoricalFinancialMetrics
from investor8-sdk.models.historical_return import HistoricalReturn
from investor8-sdk.models.historical_returns_dto import HistoricalReturnsDto
from investor8-sdk.models.historical_value_metrics import HistoricalValueMetrics
from investor8-sdk.models.history_length import HistoryLength
from investor8-sdk.models.latest_financial_metrics_dto import LatestFinancialMetricsDto
from investor8-sdk.models.latest_financials_dto import LatestFinancialsDto
from investor8-sdk.models.latest_financials_with_growth_dto import LatestFinancialsWithGrowthDto
from investor8-sdk.models.latest_price_dto import LatestPriceDto
from investor8-sdk.models.list_exchange_sector_dto import ListExchangeSectorDto
from investor8-sdk.models.login_user_dto import LoginUserDto
from investor8-sdk.models.market_highlight import MarketHighlight
from investor8-sdk.models.market_highlight_dto import MarketHighlightDto
from investor8-sdk.models.market_highlight_status import MarketHighlightStatus
from investor8-sdk.models.metrics import Metrics
from investor8-sdk.models.momentum_metric_dto import MomentumMetricDto
from investor8-sdk.models.monthly_metrics import MonthlyMetrics
from investor8-sdk.models.monthly_returns import MonthlyReturns
from investor8-sdk.models.news_categories_dto import NewsCategoriesDto
from investor8-sdk.models.news_source import NewsSource
from investor8-sdk.models.period_metric_value import PeriodMetricValue
from investor8-sdk.models.period_return import PeriodReturn
from investor8-sdk.models.plot_detail_dto import PlotDetailDto
from investor8-sdk.models.plot_dto import PlotDto
from investor8-sdk.models.plot_response_dto import PlotResponseDto
from investor8-sdk.models.previous_close_dto import PreviousCloseDto
from investor8-sdk.models.profile_name import ProfileName
from investor8-sdk.models.recent_earning_dto import RecentEarningDto
from investor8-sdk.models.req_type import ReqType
from investor8-sdk.models.reset_password_dto import ResetPasswordDto
from investor8-sdk.models.result_field import ResultField
from investor8-sdk.models.return_metrics import ReturnMetrics
from investor8-sdk.models.sa_attributes_prices import SAAttributesPrices
from investor8-sdk.models.sa_sector_price_dto import SASectorPriceDto
from investor8-sdk.models.sector_returns_dto import SectorReturnsDto
from investor8-sdk.models.send_email_dto import SendEmailDto
from investor8-sdk.models.standardized_financial import StandardizedFinancial
from investor8-sdk.models.stock_earning_dto import StockEarningDto
from investor8-sdk.models.stock_financial import StockFinancial
from investor8-sdk.models.stock_financial_metrics import StockFinancialMetrics
from investor8-sdk.models.stock_info_dto import StockInfoDto
from investor8-sdk.models.stock_info_master_dto import StockInfoMasterDto
from investor8-sdk.models.stock_ipo import StockIpo
from investor8-sdk.models.stock_news import StockNews
from investor8-sdk.models.stock_news_details import StockNewsDetails
from investor8-sdk.models.stock_news_status import StockNewsStatus
from investor8-sdk.models.stock_popularity_details_dto import StockPopularityDetailsDto
from investor8-sdk.models.stock_popularity_dto import StockPopularityDto
from investor8-sdk.models.stock_price import StockPrice
from investor8-sdk.models.stock_price_dto import StockPriceDto
from investor8-sdk.models.stock_rating_dto import StockRatingDto
from investor8-sdk.models.stock_summary_dto import StockSummaryDto
from investor8-sdk.models.string_message_result import StringMessageResult
from investor8-sdk.models.tag_details_dto import TagDetailsDto
from investor8-sdk.models.tag_info_dto import TagInfoDto
from investor8-sdk.models.upcoming_earning_dto import UpcomingEarningDto
from investor8-sdk.models.update_plot_dto import UpdatePlotDto
from investor8-sdk.models.update_watchlist_dto import UpdateWatchlistDto
from investor8-sdk.models.user import User
from investor8-sdk.models.user_dto import UserDto
from investor8-sdk.models.validate_watchlist_name_request_dto import ValidateWatchlistNameRequestDto
from investor8-sdk.models.validate_watchlist_name_response_dto import ValidateWatchlistNameResponseDto
from investor8-sdk.models.value_metrics_dto import ValueMetricsDto
from investor8-sdk.models.view_plot_dto import ViewPlotDto
from investor8-sdk.models.watchlist import Watchlist
from investor8-sdk.models.watchlist_dto import WatchlistDto
