# coding: utf-8

"""
    Investor8.Core

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class EarningMetricsDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'next_open_return_min': 'float',
        'next_open_return_max': 'float',
        'next_open_return_avg': 'float',
        'next_open_return_std': 'float',
        'next_open_return_prp': 'float',
        'next_open_return_er': 'float',
        'next_close_return_min': 'float',
        'next_close_return_max': 'float',
        'next_close_return_avg': 'float',
        'next_close_return_std': 'float',
        'next_close_return_prp': 'float',
        'next_close_return_er': 'float',
        'intra_day_return_min': 'float',
        'intra_day_return_max': 'float',
        'intra_day_return_avg': 'float',
        'intra_day_return_std': 'float',
        'intra_day_return_prp': 'float',
        'intra_day_return_er': 'float',
        'num_eps_beat': 'int',
        'num_eps_miss': 'int',
        'num_rev_beat': 'int',
        'num_rev_miss': 'int'
    }

    attribute_map = {
        'next_open_return_min': 'NextOpenReturnMin',
        'next_open_return_max': 'NextOpenReturnMax',
        'next_open_return_avg': 'NextOpenReturnAvg',
        'next_open_return_std': 'NextOpenReturnStd',
        'next_open_return_prp': 'NextOpenReturnPRP',
        'next_open_return_er': 'NextOpenReturnER',
        'next_close_return_min': 'NextCloseReturnMin',
        'next_close_return_max': 'NextCloseReturnMax',
        'next_close_return_avg': 'NextCloseReturnAvg',
        'next_close_return_std': 'NextCloseReturnStd',
        'next_close_return_prp': 'NextCloseReturnPRP',
        'next_close_return_er': 'NextCloseReturnER',
        'intra_day_return_min': 'IntraDayReturnMin',
        'intra_day_return_max': 'IntraDayReturnMax',
        'intra_day_return_avg': 'IntraDayReturnAvg',
        'intra_day_return_std': 'IntraDayReturnStd',
        'intra_day_return_prp': 'IntraDayReturnPRP',
        'intra_day_return_er': 'IntraDayReturnER',
        'num_eps_beat': 'NumEpsBeat',
        'num_eps_miss': 'NumEpsMiss',
        'num_rev_beat': 'NumRevBeat',
        'num_rev_miss': 'NumRevMiss'
    }

    def __init__(self, next_open_return_min=None, next_open_return_max=None, next_open_return_avg=None, next_open_return_std=None, next_open_return_prp=None, next_open_return_er=None, next_close_return_min=None, next_close_return_max=None, next_close_return_avg=None, next_close_return_std=None, next_close_return_prp=None, next_close_return_er=None, intra_day_return_min=None, intra_day_return_max=None, intra_day_return_avg=None, intra_day_return_std=None, intra_day_return_prp=None, intra_day_return_er=None, num_eps_beat=None, num_eps_miss=None, num_rev_beat=None, num_rev_miss=None):  # noqa: E501
        """EarningMetricsDto - a model defined in Swagger"""  # noqa: E501
        self._next_open_return_min = None
        self._next_open_return_max = None
        self._next_open_return_avg = None
        self._next_open_return_std = None
        self._next_open_return_prp = None
        self._next_open_return_er = None
        self._next_close_return_min = None
        self._next_close_return_max = None
        self._next_close_return_avg = None
        self._next_close_return_std = None
        self._next_close_return_prp = None
        self._next_close_return_er = None
        self._intra_day_return_min = None
        self._intra_day_return_max = None
        self._intra_day_return_avg = None
        self._intra_day_return_std = None
        self._intra_day_return_prp = None
        self._intra_day_return_er = None
        self._num_eps_beat = None
        self._num_eps_miss = None
        self._num_rev_beat = None
        self._num_rev_miss = None
        self.discriminator = None
        if next_open_return_min is not None:
            self.next_open_return_min = next_open_return_min
        if next_open_return_max is not None:
            self.next_open_return_max = next_open_return_max
        if next_open_return_avg is not None:
            self.next_open_return_avg = next_open_return_avg
        if next_open_return_std is not None:
            self.next_open_return_std = next_open_return_std
        if next_open_return_prp is not None:
            self.next_open_return_prp = next_open_return_prp
        if next_open_return_er is not None:
            self.next_open_return_er = next_open_return_er
        if next_close_return_min is not None:
            self.next_close_return_min = next_close_return_min
        if next_close_return_max is not None:
            self.next_close_return_max = next_close_return_max
        if next_close_return_avg is not None:
            self.next_close_return_avg = next_close_return_avg
        if next_close_return_std is not None:
            self.next_close_return_std = next_close_return_std
        if next_close_return_prp is not None:
            self.next_close_return_prp = next_close_return_prp
        if next_close_return_er is not None:
            self.next_close_return_er = next_close_return_er
        if intra_day_return_min is not None:
            self.intra_day_return_min = intra_day_return_min
        if intra_day_return_max is not None:
            self.intra_day_return_max = intra_day_return_max
        if intra_day_return_avg is not None:
            self.intra_day_return_avg = intra_day_return_avg
        if intra_day_return_std is not None:
            self.intra_day_return_std = intra_day_return_std
        if intra_day_return_prp is not None:
            self.intra_day_return_prp = intra_day_return_prp
        if intra_day_return_er is not None:
            self.intra_day_return_er = intra_day_return_er
        if num_eps_beat is not None:
            self.num_eps_beat = num_eps_beat
        if num_eps_miss is not None:
            self.num_eps_miss = num_eps_miss
        if num_rev_beat is not None:
            self.num_rev_beat = num_rev_beat
        if num_rev_miss is not None:
            self.num_rev_miss = num_rev_miss

    @property
    def next_open_return_min(self):
        """Gets the next_open_return_min of this EarningMetricsDto.  # noqa: E501


        :return: The next_open_return_min of this EarningMetricsDto.  # noqa: E501
        :rtype: float
        """
        return self._next_open_return_min

    @next_open_return_min.setter
    def next_open_return_min(self, next_open_return_min):
        """Sets the next_open_return_min of this EarningMetricsDto.


        :param next_open_return_min: The next_open_return_min of this EarningMetricsDto.  # noqa: E501
        :type: float
        """

        self._next_open_return_min = next_open_return_min

    @property
    def next_open_return_max(self):
        """Gets the next_open_return_max of this EarningMetricsDto.  # noqa: E501


        :return: The next_open_return_max of this EarningMetricsDto.  # noqa: E501
        :rtype: float
        """
        return self._next_open_return_max

    @next_open_return_max.setter
    def next_open_return_max(self, next_open_return_max):
        """Sets the next_open_return_max of this EarningMetricsDto.


        :param next_open_return_max: The next_open_return_max of this EarningMetricsDto.  # noqa: E501
        :type: float
        """

        self._next_open_return_max = next_open_return_max

    @property
    def next_open_return_avg(self):
        """Gets the next_open_return_avg of this EarningMetricsDto.  # noqa: E501


        :return: The next_open_return_avg of this EarningMetricsDto.  # noqa: E501
        :rtype: float
        """
        return self._next_open_return_avg

    @next_open_return_avg.setter
    def next_open_return_avg(self, next_open_return_avg):
        """Sets the next_open_return_avg of this EarningMetricsDto.


        :param next_open_return_avg: The next_open_return_avg of this EarningMetricsDto.  # noqa: E501
        :type: float
        """

        self._next_open_return_avg = next_open_return_avg

    @property
    def next_open_return_std(self):
        """Gets the next_open_return_std of this EarningMetricsDto.  # noqa: E501


        :return: The next_open_return_std of this EarningMetricsDto.  # noqa: E501
        :rtype: float
        """
        return self._next_open_return_std

    @next_open_return_std.setter
    def next_open_return_std(self, next_open_return_std):
        """Sets the next_open_return_std of this EarningMetricsDto.


        :param next_open_return_std: The next_open_return_std of this EarningMetricsDto.  # noqa: E501
        :type: float
        """

        self._next_open_return_std = next_open_return_std

    @property
    def next_open_return_prp(self):
        """Gets the next_open_return_prp of this EarningMetricsDto.  # noqa: E501


        :return: The next_open_return_prp of this EarningMetricsDto.  # noqa: E501
        :rtype: float
        """
        return self._next_open_return_prp

    @next_open_return_prp.setter
    def next_open_return_prp(self, next_open_return_prp):
        """Sets the next_open_return_prp of this EarningMetricsDto.


        :param next_open_return_prp: The next_open_return_prp of this EarningMetricsDto.  # noqa: E501
        :type: float
        """

        self._next_open_return_prp = next_open_return_prp

    @property
    def next_open_return_er(self):
        """Gets the next_open_return_er of this EarningMetricsDto.  # noqa: E501


        :return: The next_open_return_er of this EarningMetricsDto.  # noqa: E501
        :rtype: float
        """
        return self._next_open_return_er

    @next_open_return_er.setter
    def next_open_return_er(self, next_open_return_er):
        """Sets the next_open_return_er of this EarningMetricsDto.


        :param next_open_return_er: The next_open_return_er of this EarningMetricsDto.  # noqa: E501
        :type: float
        """

        self._next_open_return_er = next_open_return_er

    @property
    def next_close_return_min(self):
        """Gets the next_close_return_min of this EarningMetricsDto.  # noqa: E501


        :return: The next_close_return_min of this EarningMetricsDto.  # noqa: E501
        :rtype: float
        """
        return self._next_close_return_min

    @next_close_return_min.setter
    def next_close_return_min(self, next_close_return_min):
        """Sets the next_close_return_min of this EarningMetricsDto.


        :param next_close_return_min: The next_close_return_min of this EarningMetricsDto.  # noqa: E501
        :type: float
        """

        self._next_close_return_min = next_close_return_min

    @property
    def next_close_return_max(self):
        """Gets the next_close_return_max of this EarningMetricsDto.  # noqa: E501


        :return: The next_close_return_max of this EarningMetricsDto.  # noqa: E501
        :rtype: float
        """
        return self._next_close_return_max

    @next_close_return_max.setter
    def next_close_return_max(self, next_close_return_max):
        """Sets the next_close_return_max of this EarningMetricsDto.


        :param next_close_return_max: The next_close_return_max of this EarningMetricsDto.  # noqa: E501
        :type: float
        """

        self._next_close_return_max = next_close_return_max

    @property
    def next_close_return_avg(self):
        """Gets the next_close_return_avg of this EarningMetricsDto.  # noqa: E501


        :return: The next_close_return_avg of this EarningMetricsDto.  # noqa: E501
        :rtype: float
        """
        return self._next_close_return_avg

    @next_close_return_avg.setter
    def next_close_return_avg(self, next_close_return_avg):
        """Sets the next_close_return_avg of this EarningMetricsDto.


        :param next_close_return_avg: The next_close_return_avg of this EarningMetricsDto.  # noqa: E501
        :type: float
        """

        self._next_close_return_avg = next_close_return_avg

    @property
    def next_close_return_std(self):
        """Gets the next_close_return_std of this EarningMetricsDto.  # noqa: E501


        :return: The next_close_return_std of this EarningMetricsDto.  # noqa: E501
        :rtype: float
        """
        return self._next_close_return_std

    @next_close_return_std.setter
    def next_close_return_std(self, next_close_return_std):
        """Sets the next_close_return_std of this EarningMetricsDto.


        :param next_close_return_std: The next_close_return_std of this EarningMetricsDto.  # noqa: E501
        :type: float
        """

        self._next_close_return_std = next_close_return_std

    @property
    def next_close_return_prp(self):
        """Gets the next_close_return_prp of this EarningMetricsDto.  # noqa: E501


        :return: The next_close_return_prp of this EarningMetricsDto.  # noqa: E501
        :rtype: float
        """
        return self._next_close_return_prp

    @next_close_return_prp.setter
    def next_close_return_prp(self, next_close_return_prp):
        """Sets the next_close_return_prp of this EarningMetricsDto.


        :param next_close_return_prp: The next_close_return_prp of this EarningMetricsDto.  # noqa: E501
        :type: float
        """

        self._next_close_return_prp = next_close_return_prp

    @property
    def next_close_return_er(self):
        """Gets the next_close_return_er of this EarningMetricsDto.  # noqa: E501


        :return: The next_close_return_er of this EarningMetricsDto.  # noqa: E501
        :rtype: float
        """
        return self._next_close_return_er

    @next_close_return_er.setter
    def next_close_return_er(self, next_close_return_er):
        """Sets the next_close_return_er of this EarningMetricsDto.


        :param next_close_return_er: The next_close_return_er of this EarningMetricsDto.  # noqa: E501
        :type: float
        """

        self._next_close_return_er = next_close_return_er

    @property
    def intra_day_return_min(self):
        """Gets the intra_day_return_min of this EarningMetricsDto.  # noqa: E501


        :return: The intra_day_return_min of this EarningMetricsDto.  # noqa: E501
        :rtype: float
        """
        return self._intra_day_return_min

    @intra_day_return_min.setter
    def intra_day_return_min(self, intra_day_return_min):
        """Sets the intra_day_return_min of this EarningMetricsDto.


        :param intra_day_return_min: The intra_day_return_min of this EarningMetricsDto.  # noqa: E501
        :type: float
        """

        self._intra_day_return_min = intra_day_return_min

    @property
    def intra_day_return_max(self):
        """Gets the intra_day_return_max of this EarningMetricsDto.  # noqa: E501


        :return: The intra_day_return_max of this EarningMetricsDto.  # noqa: E501
        :rtype: float
        """
        return self._intra_day_return_max

    @intra_day_return_max.setter
    def intra_day_return_max(self, intra_day_return_max):
        """Sets the intra_day_return_max of this EarningMetricsDto.


        :param intra_day_return_max: The intra_day_return_max of this EarningMetricsDto.  # noqa: E501
        :type: float
        """

        self._intra_day_return_max = intra_day_return_max

    @property
    def intra_day_return_avg(self):
        """Gets the intra_day_return_avg of this EarningMetricsDto.  # noqa: E501


        :return: The intra_day_return_avg of this EarningMetricsDto.  # noqa: E501
        :rtype: float
        """
        return self._intra_day_return_avg

    @intra_day_return_avg.setter
    def intra_day_return_avg(self, intra_day_return_avg):
        """Sets the intra_day_return_avg of this EarningMetricsDto.


        :param intra_day_return_avg: The intra_day_return_avg of this EarningMetricsDto.  # noqa: E501
        :type: float
        """

        self._intra_day_return_avg = intra_day_return_avg

    @property
    def intra_day_return_std(self):
        """Gets the intra_day_return_std of this EarningMetricsDto.  # noqa: E501


        :return: The intra_day_return_std of this EarningMetricsDto.  # noqa: E501
        :rtype: float
        """
        return self._intra_day_return_std

    @intra_day_return_std.setter
    def intra_day_return_std(self, intra_day_return_std):
        """Sets the intra_day_return_std of this EarningMetricsDto.


        :param intra_day_return_std: The intra_day_return_std of this EarningMetricsDto.  # noqa: E501
        :type: float
        """

        self._intra_day_return_std = intra_day_return_std

    @property
    def intra_day_return_prp(self):
        """Gets the intra_day_return_prp of this EarningMetricsDto.  # noqa: E501


        :return: The intra_day_return_prp of this EarningMetricsDto.  # noqa: E501
        :rtype: float
        """
        return self._intra_day_return_prp

    @intra_day_return_prp.setter
    def intra_day_return_prp(self, intra_day_return_prp):
        """Sets the intra_day_return_prp of this EarningMetricsDto.


        :param intra_day_return_prp: The intra_day_return_prp of this EarningMetricsDto.  # noqa: E501
        :type: float
        """

        self._intra_day_return_prp = intra_day_return_prp

    @property
    def intra_day_return_er(self):
        """Gets the intra_day_return_er of this EarningMetricsDto.  # noqa: E501


        :return: The intra_day_return_er of this EarningMetricsDto.  # noqa: E501
        :rtype: float
        """
        return self._intra_day_return_er

    @intra_day_return_er.setter
    def intra_day_return_er(self, intra_day_return_er):
        """Sets the intra_day_return_er of this EarningMetricsDto.


        :param intra_day_return_er: The intra_day_return_er of this EarningMetricsDto.  # noqa: E501
        :type: float
        """

        self._intra_day_return_er = intra_day_return_er

    @property
    def num_eps_beat(self):
        """Gets the num_eps_beat of this EarningMetricsDto.  # noqa: E501


        :return: The num_eps_beat of this EarningMetricsDto.  # noqa: E501
        :rtype: int
        """
        return self._num_eps_beat

    @num_eps_beat.setter
    def num_eps_beat(self, num_eps_beat):
        """Sets the num_eps_beat of this EarningMetricsDto.


        :param num_eps_beat: The num_eps_beat of this EarningMetricsDto.  # noqa: E501
        :type: int
        """

        self._num_eps_beat = num_eps_beat

    @property
    def num_eps_miss(self):
        """Gets the num_eps_miss of this EarningMetricsDto.  # noqa: E501


        :return: The num_eps_miss of this EarningMetricsDto.  # noqa: E501
        :rtype: int
        """
        return self._num_eps_miss

    @num_eps_miss.setter
    def num_eps_miss(self, num_eps_miss):
        """Sets the num_eps_miss of this EarningMetricsDto.


        :param num_eps_miss: The num_eps_miss of this EarningMetricsDto.  # noqa: E501
        :type: int
        """

        self._num_eps_miss = num_eps_miss

    @property
    def num_rev_beat(self):
        """Gets the num_rev_beat of this EarningMetricsDto.  # noqa: E501


        :return: The num_rev_beat of this EarningMetricsDto.  # noqa: E501
        :rtype: int
        """
        return self._num_rev_beat

    @num_rev_beat.setter
    def num_rev_beat(self, num_rev_beat):
        """Sets the num_rev_beat of this EarningMetricsDto.


        :param num_rev_beat: The num_rev_beat of this EarningMetricsDto.  # noqa: E501
        :type: int
        """

        self._num_rev_beat = num_rev_beat

    @property
    def num_rev_miss(self):
        """Gets the num_rev_miss of this EarningMetricsDto.  # noqa: E501


        :return: The num_rev_miss of this EarningMetricsDto.  # noqa: E501
        :rtype: int
        """
        return self._num_rev_miss

    @num_rev_miss.setter
    def num_rev_miss(self, num_rev_miss):
        """Sets the num_rev_miss of this EarningMetricsDto.


        :param num_rev_miss: The num_rev_miss of this EarningMetricsDto.  # noqa: E501
        :type: int
        """

        self._num_rev_miss = num_rev_miss

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EarningMetricsDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EarningMetricsDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
