# coding: utf-8

"""
    Investor8.Core

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GetWatchlistsByUserDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'user_id': 'str',
        'watchlists': 'list[WatchlistDto]'
    }

    attribute_map = {
        'user_id': 'UserId',
        'watchlists': 'Watchlists'
    }

    def __init__(self, user_id=None, watchlists=None):  # noqa: E501
        """GetWatchlistsByUserDto - a model defined in Swagger"""  # noqa: E501
        self._user_id = None
        self._watchlists = None
        self.discriminator = None
        if user_id is not None:
            self.user_id = user_id
        if watchlists is not None:
            self.watchlists = watchlists

    @property
    def user_id(self):
        """Gets the user_id of this GetWatchlistsByUserDto.  # noqa: E501


        :return: The user_id of this GetWatchlistsByUserDto.  # noqa: E501
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this GetWatchlistsByUserDto.


        :param user_id: The user_id of this GetWatchlistsByUserDto.  # noqa: E501
        :type: str
        """

        self._user_id = user_id

    @property
    def watchlists(self):
        """Gets the watchlists of this GetWatchlistsByUserDto.  # noqa: E501


        :return: The watchlists of this GetWatchlistsByUserDto.  # noqa: E501
        :rtype: list[WatchlistDto]
        """
        return self._watchlists

    @watchlists.setter
    def watchlists(self, watchlists):
        """Sets the watchlists of this GetWatchlistsByUserDto.


        :param watchlists: The watchlists of this GetWatchlistsByUserDto.  # noqa: E501
        :type: list[WatchlistDto]
        """

        self._watchlists = watchlists

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetWatchlistsByUserDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetWatchlistsByUserDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
