# coding: utf-8

"""
    Investor8.Core

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class StockPopularityDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'ticker': 'str',
        'score': 'float',
        'rank': 'int'
    }

    attribute_map = {
        'ticker': 'Ticker',
        'score': 'Score',
        'rank': 'Rank'
    }

    def __init__(self, ticker=None, score=None, rank=None):  # noqa: E501
        """StockPopularityDto - a model defined in Swagger"""  # noqa: E501
        self._ticker = None
        self._score = None
        self._rank = None
        self.discriminator = None
        if ticker is not None:
            self.ticker = ticker
        if score is not None:
            self.score = score
        if rank is not None:
            self.rank = rank

    @property
    def ticker(self):
        """Gets the ticker of this StockPopularityDto.  # noqa: E501


        :return: The ticker of this StockPopularityDto.  # noqa: E501
        :rtype: str
        """
        return self._ticker

    @ticker.setter
    def ticker(self, ticker):
        """Sets the ticker of this StockPopularityDto.


        :param ticker: The ticker of this StockPopularityDto.  # noqa: E501
        :type: str
        """

        self._ticker = ticker

    @property
    def score(self):
        """Gets the score of this StockPopularityDto.  # noqa: E501


        :return: The score of this StockPopularityDto.  # noqa: E501
        :rtype: float
        """
        return self._score

    @score.setter
    def score(self, score):
        """Sets the score of this StockPopularityDto.


        :param score: The score of this StockPopularityDto.  # noqa: E501
        :type: float
        """

        self._score = score

    @property
    def rank(self):
        """Gets the rank of this StockPopularityDto.  # noqa: E501


        :return: The rank of this StockPopularityDto.  # noqa: E501
        :rtype: int
        """
        return self._rank

    @rank.setter
    def rank(self, rank):
        """Sets the rank of this StockPopularityDto.


        :param rank: The rank of this StockPopularityDto.  # noqa: E501
        :type: int
        """

        self._rank = rank

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(StockPopularityDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StockPopularityDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
